### ISSUE TITLE
latest from dockerhub crashes

### ISSUE THREAD

**Issue by ironicbadger** [m1dnight/exbin#28]
There's possibly an error with the latest push to docker hub, for now i've reverted to 0.0.7 and my issue is resolved. I *assume* the issue is on the 0.1.x series of images.

```
2021-07-23T20:07:12.506067579Z
2021-07-23T20:07:12.630986112Z Crash dump is being written to: erl_crash.dump...done
2021-07-23T20:07:14.834813766Z ERROR! Config provider Config.Reader failed with:
2021-07-23T20:07:14.835941699Z ** (ArgumentError) errors were found at the given arguments:
2021-07-23T20:07:14.835957589Z
2021-07-23T20:07:14.835962679Z   * 1st argument: not a binary
2021-07-23T20:07:14.835966529Z
2021-07-23T20:07:14.835970189Z     :erlang.binary_to_integer(nil)
2021-07-23T20:07:14.835973849Z     (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6
2021-07-23T20:07:14.835977429Z     (stdlib 3.15.1) erl_eval.erl:270: :erl_eval.expr/5
2021-07-23T20:07:14.835981059Z     (stdlib 3.15.1) erl_eval.erl:446: :erl_eval.expr/5
2021-07-23T20:07:14.835993749Z     (elixir 1.12.2) src/elixir.erl:280: :elixir.recur_eval/3
2021-07-23T20:07:14.835997259Z     (elixir 1.12.2) src/elixir.erl:265: :elixir.eval_forms/3
2021-07-23T20:07:14.836000729Z     (elixir 1.12.2) lib/code.ex:656: Code.eval_string_with_error_handling/3
2021-07-23T20:07:14.836004199Z     (elixir 1.12.2) lib/config.ex:258: Config.__eval__!/3
2021-07-23T20:07:14.836007540Z
2021-07-23T20:07:14.843566208Z {"init terminating in do_boot",{badarg,[{erlang,binary_to_integer,[nil],[{error_info,#{module=>erl_erts_errors}}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,270}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,280}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,265}]},{'Elixir.Code',eval_string_with_error_handling,3,[{file,"lib/code.ex"},{line,656}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,258}]}]}}
2021-07-23T20:07:14.847522749Z init terminating in do_boot ({badarg,[{erlang,binary_to_integer,[nil],[{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{el
2021-07-23T20:07:14.847644319Z
2021-07-23T20:07:14.995538478Z Crash dump is being written to: erl_crash.dump...done
```

**Comment by m1dnight** [comment]
I'm going to guess it's an env var thats missing or so. Can you share your
docker compose file and/or env file?

**Comment by ironicbadger** [comment]
Yep - here's the ENV vars 

https://github.com/selfhostedshow/infra/blob/49ba3960f981c30b5d9769d4d9f45e5c2ec60335/ansible/group_vars/demo.yaml#L211

Nothing changed between 0.1 and 0.0.7, did you add something?

**Comment by m1dnight** [comment]
Ah, darn it. I forgot about the custom logo features and whatnot. I propose you keep using 0.0.7 for now, I will do my best to get it feature-complete asap.

Version 0.1.x is basically a rewrite (upgrade from Phoenix 1.5.7 to 1.5.9 and Elixir 1.4 to 1.12). 

Master now points to v2 (0.1.x) and v1 (0.0.x) is a separate branch. .

**Comment by ironicbadger** [comment]
No worries. My fault really for running :latest in production. 

Btw, https://paste.docs.lol is our networks pastebin now. We use it for all our shows at Jupiter Broadcasting - thanks for all you do.

**Comment by m1dnight** [comment]
Oh, that looks really cool! Thanks for using something I built!

I will get on this asap.

**Comment by m1dnight** [comment]
Small update: I added the custom logo and branding to the new version. Will do some more work soon.

/ m1dnight
