### ISSUE TITLE
Internal Server Error when loading stats page

### ISSUE THREAD

**Issue by joshproehl** [m1dnight/exbin#34]
On a docker-hosted 0.0.7 instance which has just been upgraded to 0.1.4, loading the stats page results in the following error:
```
14:59:39.316 request_id=Fpvh0U8mYQ15uLUAAARR [info] GET /snippet/statistics
14:59:39.326 request_id=Fpvh0U8mYQ15uLUAAARR [info] Sent 500 in 9ms
14:59:39.328 [error] #PID<0.3705.0> running ExBinWeb.Endpoint (connection #PID<0.3703.0>, stream id 2) terminated
Server: [REDACTED] (http)
Request: GET /snippet/statistics
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: nil
        (exbin 0.1.4) lib/exbin/stats.ex:112: anonymous fn/3 in ExBin.Stats.count_per_month/0
        (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
        (exbin 0.1.4) lib/exbin/stats.ex:109: ExBin.Stats.count_per_month/0
        (exbin 0.1.4) lib/exbin_web/controllers/snippet_controller.ex:83: ExBinWeb.SnippetController.statistics/2
        (exbin 0.1.4) lib/exbin_web/controllers/snippet_controller.ex:1: ExBinWeb.SnippetController.action/2
        (exbin 0.1.4) lib/exbin_web/controllers/snippet_controller.ex:1: ExBinWeb.SnippetController.phoenix_controller_pipeline/2
        (phoenix 1.5.9) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (exbin 0.1.4) lib/exbin_web/endpoint.ex:1: ExBinWeb.Endpoint.plug_builder_call/2
```
Since I'm not having any luck reproducing this locally I opened up a remote console on my instance and took a look at [the code](https://github.com/m1dnight/exbin/blob/8b5d295dac92d52d14ec8d95f502b02a4d02c218/lib/exbin/stats.ex#L112) by copying it into the IEx shell.

What it spat out for this chunk:
```
      Enum.reduce(result, buckets, fn r, buckets ->
      IO.inspect(r, label: "Results")
      IO.inspect(buckets, label: "Buckets")
        r = %{r | month: DateTime.shift_zone!(r.month, timezone)}
        IO.inspect(r, label: "Results-in-reduce")
      end)
```
revealed:
```
Results: %{count: 3, month: ~U[2021-06-01 00:00:00.000000Z], private: false} 
Buckets: %{
  #DateTime<2021-01-01 00:00:00.000000-06:00 CST America/Chicago> => {0, 0},
  #DateTime<2021-02-01 00:00:00.000000-06:00 CST America/Chicago> => {0, 0},
  #DateTime<2021-03-01 00:00:00.000000-06:00 CST America/Chicago> => {0, 0},
  #DateTime<2021-04-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2021-05-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2021-06-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2021-07-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2021-08-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2020-09-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2020-10-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2020-11-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2020-12-01 00:00:00.000000-06:00 CST America/Chicago> => {0, 0}
}
Results-in-reduce: %{
  count: 3,
  month: #DateTime<2021-05-31 19:00:00.000000-05:00 CDT America/Chicago>,
  private: false
}
```
Which shows why the `Map.get(buckets, r.month)` returns nil and crashes the whole thing at least. (The shifted time isn't a month-start time, but 5 hours earlier, indicating perhaps it didn't need to be shifted?)

Unfortunately I'm out of time for this now, but I'll try and get back and do a test case for this to try and figure out why it's happening. (Maybe it's a configuration issue on my instance, or perhaps a result of having upgraded.)

**Comment by m1dnight** [comment]
I've had the same issue before. It has to do with timezones. I will have a look.

**Comment by m1dnight** [comment]
Just to be sure, can you confirm that both the database and the front-end are running in the same timezone? 

Ah, I see: 

```
  #DateTime<2020-11-01 00:00:00.000000-05:00 CDT America/Chicago> => {0, 0},
  #DateTime<2020-12-01 00:00:00.000000-06:00 CST America/Chicago> => {0, 0}
```

CST/CDT might be the cause. Digging deeper !
