### ISSUE TITLE
App entrypoint errors with 0.1.7 and search issues

### ISSUE THREAD

**Issue by pezhore** [m1dnight/exbin#46]
Hello! I'm trying to get exbin going for an internal event and I'm running into two issues - one of which is a quick fix, the other, not so much.

## Trailing `\r` in entrypoint

It looks like the good, ol' Dos carriage return is at the end of every line in `entrypoint.sh`:

```
range@exbin:/opt/exbin$ docker-compose up
WARNING: The DEBUG variable is not set. Defaulting to a blank string.
Creating network "exbin_internal" with the default driver
Creating exbin_db_1 ... done
Creating exbin_exbin_1 ... done
Attaching to exbin_db_1, exbin_exbin_1
db_1     |
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     |
db_1     | 2022-08-28 14:22:30.185 CDT [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1     | 2022-08-28 14:22:30.185 CDT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2022-08-28 14:22:30.185 CDT [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2022-08-28 14:22:30.188 CDT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2022-08-28 14:22:30.193 CDT [26] LOG:  database system was shut down at 2022-08-28 14:22:03 CDT
db_1     | 2022-08-28 14:22:30.197 CDT [1] LOG:  database system is ready to accept connections
exbin_1  | /app/entrypoint.sh: line 4: $'\r': command not found
: No such file or directorysh: line 6: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 7: $'\r': command not found
: No such file or directorysh: line 9: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 10: $'\r': command not found
: No such file or directorysh: line 12: /app/prod/bin/prod
exbin_exbin_1 exited with code 127
exbin_1  | /app/entrypoint.sh: line 4: $'\r': command not found
: No such file or directorysh: line 6: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 7: $'\r': command not found
: No such file or directorysh: line 9: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 10: $'\r': command not found
: No such file or directorysh: line 12: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 4: $'\r': command not found
: No such file or directorysh: line 6: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 7: $'\r': command not found
: No such file or directorysh: line 9: /app/prod/bin/prod
exbin_1  | /app/entrypoint.sh: line 10: $'\r': command not found
: No such file or directorysh: line 12: /app/prod/bin/prod
exbin_exbin_1 exited with code 127
^CGracefully stopping... (press Ctrl+C again to force)
```

I can re-author the container locally to strip out the carriage return char, but then I run into a different, more challenging error...

## Live Search Failing

Search throws the follow error:

```
db_1     | 2022-08-28 14:24:51.612 CDT [52] ERROR:  operator does not exist: bytea ~~* unknown at character 179
db_1     | 2022-08-28 14:24:51.612 CDT [52] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
db_1     | 2022-08-28 14:24:51.612 CDT [52] STATEMENT:  SELECT s0."id", s0."name", s0."content", s0."viewcount", s0."private", s0."ephemeral", s0."user_id", s0."inserted_at", s0."updated_at" FROM "snippets" AS s0 WHERE ((s0."content" ILIKE $1) AND (s0."private" = FALSE)) ORDER BY s0."inserted_at" DESC
exbin_1  | 14:24:51.613 [error] GenServer #PID<0.4033.0> terminating
exbin_1  | ** (Postgrex.Error) ERROR 42883 (undefined_function) operator does not exist: bytea ~~* unknown
exbin_1  |
exbin_1  |     query: SELECT s0."id", s0."name", s0."content", s0."viewcount", s0."private", s0."ephemeral", s0."user_id", s0."inserted_at", s0."updated_at" FROM "snippets" AS s0 WHERE ((s0."content" ILIKE $1) AND (s0."private" = FALSE)) ORDER BY s0."inserted_at" DESC
exbin_1  |
exbin_1  |     hint: No operator matches the given name and argument types. You might need to add explicit type casts.
exbin_1  |     (db_connection 2.4.0) lib/db_connection.ex:1265: DBConnection.prepare_declare!/4
exbin_1  |     (db_connection 2.4.0) lib/db_connection.ex:1044: anonymous fn/4 in DBConnection.reduce/3
exbin_1  |     (elixir 1.12.3) lib/stream.ex:1517: anonymous fn/5 in Stream.resource/3
exbin_1  |     (elixir 1.12.3) lib/stream.ex:1719: Enumerable.Stream.do_each/4
exbin_1  |     (elixir 1.12.3) lib/stream.ex:880: Stream.do_transform/5
exbin_1  |     (elixir 1.12.3) lib/stream.ex:1719: Enumerable.Stream.do_each/4
exbin_1  |     (elixir 1.12.3) lib/stream.ex:649: Stream.run/1
exbin_1  |     (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:1017: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
exbin_1  | Last message: %Phoenix.Socket.Message{event: "event", join_ref: "6", payload: %{"event" => "suggest", "type" => "form", "uploads" => %{}, "value" => "q=as&_target=q"}, ref: "7", topic: "lv:phx-Fw-YtG6Mx7DSXAAi"}
^CGracefully stopping... (press Ctrl+C again to force)
```

Here's my `docker-compose.yml`, `.env`, and the `Dockerfile` that fixes the carriage returns [gist](https://gist.github.com/pezhore/7fe5600fa587dbf7a1b2335db75a1e8e)

I've tested the most recent docker containers from docker hub:

| Version | Result |
| --- | --- |
| `latest` | Fails with `1st argument: not an atom` error | 
| `0.1.6-dev.5` | Fails with same error as latest |
| `0.1.7` | Fails with carriage return error |
| `0.1.7` (with `\r` fix) | Fails with `operator does not exist: bytea ~~* unknown at character 179` |
|`0.1.6-dev.2` | **Search works ... sort of (see below)** |
|`0.1.6` | Snippets don't seem to save/Search broken|

For version `0.1.6-dev.2` - search result populates, but doesn't seem to actually limit the results. 
![image](https://user-images.githubusercontent.com/7430984/187092214-883e3259-794d-47cf-829f-3434a386129c.png)

Edit: Evidently the search showing everything is only when a user is logged in for version `0.1.6-dev.2`.

**Comment by m1dnight** [comment]
Heh, that's odd. I'll have a look at it today, thanks for letting me know!

Aug 28, 2022 21:36:08 Brian Marsh ***@***.***>:

**Comment by m1dnight** [comment]
The issue with the live search should be resolved now. I havent had the time to test it thoroughly, but I did figure out what was wrong and resolved it. 

Regarding the entrypoint, I don't see those line endings on my end. I'll give that a test later today.

**Comment by m1dnight** [comment]
Just noticed now that you mentioned the limit, too. I'll have a look at that too.

**Comment by m1dnight** [comment]
I've built the new container and it works as far as I can tell. The container should be up in a few minutes under the 0.1.7 tag. Let me know if that fixed your issues.
