### ISSUE TITLE
Error After Upgrade

### ISSUE THREAD

**Issue by jordantrizz** [m1dnight/exbin#56]
Getting the following after upgrading to the latest exbin docker image

```
Attaching to exbin, exbin_db
db_1     |
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     |
db_1     | 2023-05-18 12:48:01.147 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2023-05-18 12:48:01.147 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2023-05-18 12:48:01.174 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-05-18 12:48:01.224 UTC [20] LOG:  database system was shut down at 2023-05-18 12:48:00 UTC
db_1     | 2023-05-18 12:48:01.237 UTC [1] LOG:  database system is ready to accept connections
db_1     | 2023-05-18 12:48:06.119 UTC [28] ERROR:  invalid input syntax for type bytea
db_1     | 2023-05-18 12:48:06.119 UTC [28] STATEMENT:  ALTER TABLE snippets
db_1     |      ALTER COLUMN content TYPE bytea
db_1     |      USING content::bytea;
db_1     |
exbin    | ** (Postgrex.Error) ERROR 22P02 (invalid_text_representation) invalid input syntax for type bytea
exbin    |     (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
exbin    |     (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
exbin    |     (ecto_sql 3.6.2) lib/ecto/adapters/sql.ex:848: Ecto.Adapters.SQL.execute_ddl/4
exbin    |     (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
exbin    |     (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
exbin    |     (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
exbin    |     (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
exbin    |     (ecto_sql 3.6.2) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
exbin    | Did not create a user because there are already registered users in the database.
```

**Comment by m1dnight** [comment]
I tried to reproduce this but I did not manage to do so. I assume some snippet contains weird data?
