### ISSUE TITLE
Docker Image Fails to Build - code: 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by jordantrizz** [m1dnight/exbin#58]
The docker image fails to build.

```
❯ docker build .
[+] Building 411.5s (20/29)                                                                                                                                                                                     docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                      0.1s
 => => transferring dockerfile: 1.61kB                                                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/elixir:1.15-slim                                                                                                                                                       1.4s
 => [auth] library/elixir:pull token for registry-1.docker.io                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                         0.1s
 => => transferring context: 95B                                                                                                                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                                         0.2s
 => => transferring context: 749.19kB                                                                                                                                                                                     0.1s
 => [build  1/17] FROM docker.io/library/elixir:1.15-slim@sha256:4bbe06fef74b85cc9e55a9303f76728be60697c3c2aace551b10e17ddac678f1                                                                                        10.5s
 => => resolve docker.io/library/elixir:1.15-slim@sha256:4bbe06fef74b85cc9e55a9303f76728be60697c3c2aace551b10e17ddac678f1                                                                                                 0.1s
 => => sha256:db355abd2760f38a8528fa579cd729e6250e4ee57a3e297d497033725175eb0a 1.54kB / 1.54kB                                                                                                                            0.0s
 => => sha256:293399e0bc33231c482432283dbb4f4a2b69e424fe3c8c1e39441e601d1d4f08 5.07kB / 5.07kB                                                                                                                            0.0s
 => => sha256:7d98d813d54f6207a57721008a4081378343ad8f1b2db66c121406019171805b 49.56MB / 49.56MB                                                                                                                          1.4s
 => => sha256:26c92377ed0844dd1ef966ba4c4d666ab55b7b84755b85eaa9c22f588e93fa7b 70.32MB / 70.32MB                                                                                                                          2.4s
 => => sha256:4bbe06fef74b85cc9e55a9303f76728be60697c3c2aace551b10e17ddac678f1 7.67kB / 7.67kB                                                                                                                            0.0s
 => => sha256:d941fef6c658350e58b8f0bd57ea58d3f115d6c17e4069cc7a3937bfb3191ef1 6.81MB / 6.81MB                                                                                                                            0.7s
 => => extracting sha256:7d98d813d54f6207a57721008a4081378343ad8f1b2db66c121406019171805b                                                                                                                                 4.1s
 => => extracting sha256:26c92377ed0844dd1ef966ba4c4d666ab55b7b84755b85eaa9c22f588e93fa7b                                                                                                                                 3.6s
 => => extracting sha256:d941fef6c658350e58b8f0bd57ea58d3f115d6c17e4069cc7a3937bfb3191ef1                                                                                                                                 0.5s
 => [app 2/8] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssl postgresql-client locales                                                                                                  18.7s
 => [build  2/17] RUN apt-get update && apt-get install -y git nodejs npm yarn python3                                                                                                                                  235.8s
 => [app 3/8] RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen &&     locale-gen                                                                                                                                        3.2s
 => [app 4/8] RUN mkdir /app                                                                                                                                                                                              0.9s
 => [app 5/8] WORKDIR /app                                                                                                                                                                                                0.6s
 => [build  3/17] RUN mkdir /app                                                                                                                                                                                          0.5s
 => [build  4/17] WORKDIR /app                                                                                                                                                                                            0.2s
 => [build  5/17] RUN mix do local.hex --force, local.rebar --force                                                                                                                                                       2.2s
 => [build  6/17] COPY mix.exs mix.lock ./                                                                                                                                                                                0.2s
 => [build  7/17] COPY config config                                                                                                                                                                                      0.2s
 => [build  8/17] RUN mix deps.get --only prod                                                                                                                                                                            7.0s
 => [build  9/17] RUN mix deps.compile                                                                                                                                                                                  119.4s
 => [build 10/17] COPY assets assets                                                                                                                                                                                      0.2s
 => ERROR [build 11/17] RUN npm install --prefix ./assets && npm run deploy --prefix ./assets                                                                                                                            33.6s
------
 > [build 11/17] RUN npm install --prefix ./assets && npm run deploy --prefix ./assets:
9.490 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
10.35 npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
10.35 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
10.62 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
11.20 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
11.38 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
11.77 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
12.92 npm WARN deprecated is-accessor-descriptor@1.0.0: Please upgrade to v1.0.1
13.01 npm WARN deprecated is-data-descriptor@1.0.0: Please upgrade to v1.0.1
13.39 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
13.99 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
14.01 npm WARN deprecated figgy-pudding@3.5.2: This module is no longer supported.
16.09 npm WARN deprecated abab@1.0.4: Use your platform's native atob() and btoa() methods instead
16.77 npm WARN deprecated @babel/plugin-proposal-private-methods@7.13.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
16.80 npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
16.80 npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
16.84 npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.12.13: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
16.84 npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
16.89 npm WARN deprecated @babel/plugin-proposal-private-property-in-object@7.14.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
16.89 npm WARN deprecated @babel/plugin-proposal-class-properties@7.13.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
16.93 npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
17.10 npm WARN deprecated @babel/plugin-proposal-class-static-block@7.14.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-static-block instead.
17.10 npm WARN deprecated @babel/plugin-proposal-dynamic-import@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
17.10 npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
17.15 npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.14.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
17.20 npm WARN deprecated @babel/plugin-proposal-export-namespace-from@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
17.20 npm WARN deprecated @babel/plugin-proposal-json-strings@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
17.20 npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.14.2: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
18.16 npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
18.29 npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
18.37 npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
18.38 npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
18.65 npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
18.74 npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
18.85 npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
18.85 npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
19.30 npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
19.31 npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
19.45 npm WARN deprecated is-accessor-descriptor@0.1.6: Please upgrade to v0.1.7
19.47 npm WARN deprecated is-data-descriptor@0.1.4: Please upgrade to v0.1.5
21.04 npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
28.39
28.39 added 886 packages, and audited 887 packages in 27s
28.39
28.39 50 packages are looking for funding
28.39   run `npm fund` for details
28.54
28.54 84 vulnerabilities (1 low, 52 moderate, 26 high, 5 critical)
28.54
28.54 To address issues that do not require attention, run:
28.54   npm audit fix
28.54
28.54 To address all issues possible (including breaking changes), run:
28.54   npm audit fix --force
28.54
28.54 Some issues need review, and may require choosing
28.54 a different dependency.
28.54
28.54 Run `npm audit` for details.
29.56
29.56 > deploy
29.56 > webpack --mode production
29.56
31.92 Browserslist: caniuse-lite is outdated. Please run:
31.92 npx browserslist@latest --update-db
31.92
31.92 Why you should do it regularly:
31.92 https://github.com/browserslist/browserslist#browsers-data-updating
32.78 node:internal/crypto/hash:69
32.78   this[kHandle] = new _Hash(algorithm, xofLen);
32.78                   ^
32.78
32.78 Error: error:0308010C:digital envelope routines::unsupported
32.78     at new Hash (node:internal/crypto/hash:69:19)
32.78     at Object.createHash (node:crypto:133:10)
32.78     at module.exports (/app/assets/node_modules/webpack/lib/util/createHash.js:135:53)
32.78     at NormalModule._initBuildHash (/app/assets/node_modules/webpack/lib/NormalModule.js:417:16)
32.78     at handleParseError (/app/assets/node_modules/webpack/lib/NormalModule.js:471:10)
32.78     at /app/assets/node_modules/webpack/lib/NormalModule.js:503:5
32.78     at /app/assets/node_modules/webpack/lib/NormalModule.js:358:12
32.78     at /app/assets/node_modules/loader-runner/lib/LoaderRunner.js:373:3
32.78     at iterateNormalLoaders (/app/assets/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
32.78     at iterateNormalLoaders (/app/assets/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
32.78     at /app/assets/node_modules/loader-runner/lib/LoaderRunner.js:236:3
32.78     at context.callback (/app/assets/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
32.78     at /app/assets/node_modules/babel-loader/lib/index.js:59:71 {
32.78   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
32.78   library: 'digital envelope routines',
32.78   reason: 'unsupported',
32.78   code: 'ERR_OSSL_EVP_UNSUPPORTED'
32.78 }
32.78
32.78 Node.js v18.19.0
------
Dockerfile:26
--------------------
  24 |     # Build web assets.
  25 |     COPY assets assets
  26 | >>> RUN npm install --prefix ./assets && npm run deploy --prefix ./assets
  27 |     RUN mix phx.digest
  28 |
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install --prefix ./assets && npm run deploy --prefix ./assets" did not complete successfully: exit code: 1
```

**Comment by m1dnight** [comment]
This is fixed now!
